<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <WebView2LoaderPreference>Dynamic</WebView2LoaderPreference>
    <WebView2UseWinRT>False</WebView2UseWinRT>
    <PackageLicenseExpression>MIT-Modern-Variant</PackageLicenseExpression>
    <AssemblyVersion>2.0.1.2</AssemblyVersion>
    <FileVersion>2.0.1.2</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>AdamStudio.App</StartupObject>
    <ApplicationIcon>..\AdamStudio.Core\Properties\Icons\main_app_icon.ico</ApplicationIcon>
    <PackageProjectUrl>https://github.com/Adam-Software/AdamStudio</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Adam-Software/AdamStudio</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CA1416</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdamStudio.Core\AdamStudio.Core.csproj" />
    <ProjectReference Include="..\Modules\AdamStudio.Modules.ContentRegion\AdamStudio.Modules.ContentRegion.csproj" />
    <ProjectReference Include="..\Modules\AdamStudio.Modules.FlayoutsRegion\AdamStudio.Modules.FlayoutsRegion.csproj" />
    <ProjectReference Include="..\Modules\AdamStudio.Modules.MenuRegion\AdamStudio.Modules.MenuRegion.csproj" />
    <ProjectReference Include="..\Modules\AdamStudio.Modules.StatusBar\AdamStudio.Modules.StatusBarRegion.csproj" />
    <ProjectReference Include="..\Modules\AdamStudio.Modules.ToolBarRegion\AdamStudio.Modules.ToolBarRegion.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
</Project>