[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""

[git]
commit_parsers = [
    { message = "^feat\\(shell\\)", group = "Shell - Added" },
    { message = "^fix\\(shell\\)", group = "Shell - Fixed" },
    { message = "^feat\\(core\\)", group = "Core - Added" },
    { message = "^fix\\(core\\)", group = "Core - Fixed" },
    { message = "^feat\\(services\\)", group = "Services - Added" },
    { message = "^fix\\(services\\)", group = "Services - Fixed" },
    { message = "^feat\\(controls\\)", group = "Controls - Added" },
    { message = "^fix\\(controls\\)", group = "Controls - Fixed" },
    { message = "^feat\\(menu\\)", group = "Menu - Added" },
    { message = "^fix\\(menu\\)", group = "Menu - Fixed" },
    { message = "^feat\\(content\\)", group = "Content - Added" },
    { message = "^fix\\(content\\)", group = "Content - Fixed" },
    { message = "^feat\\(status\\)", group = "Status - Added" },
    { message = "^fix\\(status\\)", group = "Status - Fixed" },
    { message = "^feat\\(flyouts\\)", group = "Flyouts - Added" },
    { message = "^fix\\(flyouts\\)", group = "Flyouts - Fixed" },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Fixed" },
    { message = "^refactor", group = "Refactored" },
    { message = "^perf", group = "Performance" },
    { message = "^docs", group = "Documentation" },
    { message = "^chore", group = "Miscellaneous" },
]

commit_sort_by = "date"
group_by = "group"
