<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="FFmpeg.zgabi.FFME.Windows.6.0.2" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MahApps.Metro.IconPacks" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Web.WebView2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="NetCoreServer" />
    <PackageReference Include="PortableSettingsProvider" />
    <PackageReference Include="Prism.Core" />
    <PackageReference Include="Prism.DryIoc" />
    <PackageReference Include="Prism.Wpf" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.DelegatingText" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.IO.FileSystem" />
    <PackageReference Include="System.Net.Primitives" />
    <PackageReference Include="Tcp.NET.Server" />
    <PackageReference Include="TcpSharp" />
    <PackageReference Include="The.Microsoft.Expression.Interactions" />
    <PackageReference Include="Websocket.Client" />
    <PackageReference Include="zgabi.FFME.Windows" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legacy\AdamBlocklyLibrary\AdamBlocklyLibrary.csproj" />
    <ProjectReference Include="..\Legacy\AdamController.WebApi.Client\AdamController.WebApi.Client.csproj" />
  </ItemGroup>

</Project>
