//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamStudio.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18000")]
        public string VideoDataExchangePort {
            get {
                return ((string)(this["VideoDataExchangePort"]));
            }
            set {
                this["VideoDataExchangePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15005")]
        public string MessageDataExchangePort {
            get {
                return ((string)(this["MessageDataExchangePort"]));
            }
            set {
                this["MessageDataExchangePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.50.10")]
        public string ServerIP {
            get {
                return ((string)(this["ServerIP"]));
            }
            set {
                this["ServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public string BaseTheme {
            get {
                return ((string)(this["BaseTheme"]));
            }
            set {
                this["BaseTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ThemeColorScheme {
            get {
                return ((string)(this["ThemeColorScheme"]));
            }
            set {
                this["ThemeColorScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplaySetBlocks {
            get {
                return ((int)(this["DisplaySetBlocks"]));
            }
            set {
                this["DisplaySetBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlocklyShowTrashcan {
            get {
                return ((bool)(this["BlocklyShowTrashcan"]));
            }
            set {
                this["BlocklyShowTrashcan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public short BlocklyGridSpacing {
            get {
                return ((short)(this["BlocklyGridSpacing"]));
            }
            set {
                this["BlocklyGridSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short BlocklyGridLenth {
            get {
                return ((short)(this["BlocklyGridLenth"]));
            }
            set {
                this["BlocklyGridLenth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyGridColour {
            get {
                return ((string)(this["BlocklyGridColour"]));
            }
            set {
                this["BlocklyGridColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklySnapToGridNodes {
            get {
                return ((bool)(this["BlocklySnapToGridNodes"]));
            }
            set {
                this["BlocklySnapToGridNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyShowGrid {
            get {
                return ((bool)(this["BlocklyShowGrid"]));
            }
            set {
                this["BlocklyShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ru")]
        public string AppLanguage {
            get {
                return ((string)(this["AppLanguage"]));
            }
            set {
                this["AppLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ru")]
        public global::AdamBlocklyLibrary.Enum.BlocklyLanguage BlocklyToolboxLanguage {
            get {
                return ((global::AdamBlocklyLibrary.Enum.BlocklyLanguage)(this["BlocklyToolboxLanguage"]));
            }
            set {
                this["BlocklyToolboxLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ru")]
        public global::AdamBlocklyLibrary.Enum.BlocklyLanguage BlocklyWorkspaceLanguage {
            get {
                return ((global::AdamBlocklyLibrary.Enum.BlocklyLanguage)(this["BlocklyWorkspaceLanguage"]));
            }
            set {
                this["BlocklyWorkspaceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyLogicCategoryState {
            get {
                return ((bool)(this["BlocklyLogicCategoryState"]));
            }
            set {
                this["BlocklyLogicCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyColorCategoryState {
            get {
                return ((bool)(this["BlocklyColorCategoryState"]));
            }
            set {
                this["BlocklyColorCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyListsCategoryState {
            get {
                return ((bool)(this["BlocklyListsCategoryState"]));
            }
            set {
                this["BlocklyListsCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyLoopCategoryState {
            get {
                return ((bool)(this["BlocklyLoopCategoryState"]));
            }
            set {
                this["BlocklyLoopCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyMathCategoryState {
            get {
                return ((bool)(this["BlocklyMathCategoryState"]));
            }
            set {
                this["BlocklyMathCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyProcedureCategoryState {
            get {
                return ((bool)(this["BlocklyProcedureCategoryState"]));
            }
            set {
                this["BlocklyProcedureCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlocklyDynamicVariableCategoryState {
            get {
                return ((bool)(this["BlocklyDynamicVariableCategoryState"]));
            }
            set {
                this["BlocklyDynamicVariableCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyVariableCategoryState {
            get {
                return ((bool)(this["BlocklyVariableCategoryState"]));
            }
            set {
                this["BlocklyVariableCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyLogicCategoryAlternateName {
            get {
                return ((string)(this["BlocklyLogicCategoryAlternateName"]));
            }
            set {
                this["BlocklyLogicCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyColourCategoryAlternateName {
            get {
                return ((string)(this["BlocklyColourCategoryAlternateName"]));
            }
            set {
                this["BlocklyColourCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyListsCategoryAlternateName {
            get {
                return ((string)(this["BlocklyListsCategoryAlternateName"]));
            }
            set {
                this["BlocklyListsCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyLoopCategoryAlternateName {
            get {
                return ((string)(this["BlocklyLoopCategoryAlternateName"]));
            }
            set {
                this["BlocklyLoopCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyMathCategoryAlternateName {
            get {
                return ((string)(this["BlocklyMathCategoryAlternateName"]));
            }
            set {
                this["BlocklyMathCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyProcedureCategoryAlternateName {
            get {
                return ((string)(this["BlocklyProcedureCategoryAlternateName"]));
            }
            set {
                this["BlocklyProcedureCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyDynamicVariableCategoryAlternateName {
            get {
                return ((string)(this["BlocklyDynamicVariableCategoryAlternateName"]));
            }
            set {
                this["BlocklyDynamicVariableCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyVariableCategoryAlternateName {
            get {
                return ((string)(this["BlocklyVariableCategoryAlternateName"]));
            }
            set {
                this["BlocklyVariableCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic")]
        public global::AdamBlocklyLibrary.Enum.BlocklyTheme BlocklyTheme {
            get {
                return ((global::AdamBlocklyLibrary.Enum.BlocklyTheme)(this["BlocklyTheme"]));
            }
            set {
                this["BlocklyTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeToolboxLanguageToggleSwitchState {
            get {
                return ((bool)(this["ChangeToolboxLanguageToggleSwitchState"]));
            }
            set {
                this["ChangeToolboxLanguageToggleSwitchState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeBlocklyThemeToggleSwitchState {
            get {
                return ((bool)(this["ChangeBlocklyThemeToggleSwitchState"]));
            }
            set {
                this["ChangeBlocklyThemeToggleSwitchState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeGridColorSwitchToggleSwitchState {
            get {
                return ((bool)(this["ChangeGridColorSwitchToggleSwitchState"]));
            }
            set {
                this["ChangeGridColorSwitchToggleSwitchState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeSpacingSwitchToggleSwitchState {
            get {
                return ((bool)(this["ChangeSpacingSwitchToggleSwitchState"]));
            }
            set {
                this["ChangeSpacingSwitchToggleSwitchState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("854")]
        public double BlocklyEditorWidth {
            get {
                return ((double)(this["BlocklyEditorWidth"]));
            }
            set {
                this["BlocklyEditorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public double BlocklySourceEditorHeight {
            get {
                return ((double)(this["BlocklySourceEditorHeight"]));
            }
            set {
                this["BlocklySourceEditorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyRestoreBlockOnLoad {
            get {
                return ((bool)(this["BlocklyRestoreBlockOnLoad"]));
            }
            set {
                this["BlocklyRestoreBlockOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedUserWorkspaceFolderPath {
            get {
                return ((string)(this["SavedUserWorkspaceFolderPath"]));
            }
            set {
                this["SavedUserWorkspaceFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedUserCustomBlocksFolderPath {
            get {
                return ((string)(this["SavedUserCustomBlocksFolderPath"]));
            }
            set {
                this["SavedUserCustomBlocksFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedUserScriptsFolderPath {
            get {
                return ((string)(this["SavedUserScriptsFolderPath"]));
            }
            set {
                this["SavedUserScriptsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedUserToolboxFolderPath {
            get {
                return ((string)(this["SavedUserToolboxFolderPath"]));
            }
            set {
                this["SavedUserToolboxFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyTextCategoryAlternateName {
            get {
                return ((string)(this["BlocklyTextCategoryAlternateName"]));
            }
            set {
                this["BlocklyTextCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyTextCategoryState {
            get {
                return ((bool)(this["BlocklyTextCategoryState"]));
            }
            set {
                this["BlocklyTextCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShadowWorkspaceInDebug {
            get {
                return ((bool)(this["ShadowWorkspaceInDebug"]));
            }
            set {
                this["ShadowWorkspaceInDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public int TcpConnectStatePort {
            get {
                return ((int)(this["TcpConnectStatePort"]));
            }
            set {
                this["TcpConnectStatePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int BenchmarkTcpSizeByteArray {
            get {
                return ((int)(this["BenchmarkTcpSizeByteArray"]));
            }
            set {
                this["BenchmarkTcpSizeByteArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.50.10")]
        public string BenchmarkTestServerIp {
            get {
                return ((string)(this["BenchmarkTestServerIp"]));
            }
            set {
                this["BenchmarkTestServerIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public int BenchmarkTestTcpServerPort {
            get {
                return ((int)(this["BenchmarkTestTcpServerPort"]));
            }
            set {
                this["BenchmarkTestTcpServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BenchmarkTestTcpClientsQty {
            get {
                return ((int)(this["BenchmarkTestTcpClientsQty"]));
            }
            set {
                this["BenchmarkTestTcpClientsQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int BenchmarkTestTcpMessageQty {
            get {
                return ((int)(this["BenchmarkTestTcpMessageQty"]));
            }
            set {
                this["BenchmarkTestTcpMessageQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BenchmarkTestTcpTime {
            get {
                return ((int)(this["BenchmarkTestTcpTime"]));
            }
            set {
                this["BenchmarkTestTcpTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BenchmarkTestUdpTime {
            get {
                return ((int)(this["BenchmarkTestUdpTime"]));
            }
            set {
                this["BenchmarkTestUdpTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16001")]
        public int BenchmarkTcpTestPort {
            get {
                return ((int)(this["BenchmarkTcpTestPort"]));
            }
            set {
                this["BenchmarkTcpTestPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16002")]
        public int BenchmarkUdpTestPort {
            get {
                return ((int)(this["BenchmarkUdpTestPort"]));
            }
            set {
                this["BenchmarkUdpTestPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int BenchmarkUdpSizeByteArray {
            get {
                return ((int)(this["BenchmarkUdpSizeByteArray"]));
            }
            set {
                this["BenchmarkUdpSizeByteArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int BenchmarkTestUdpMessageQty {
            get {
                return ((int)(this["BenchmarkTestUdpMessageQty"]));
            }
            set {
                this["BenchmarkTestUdpMessageQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BenchmarkTestUdpClientsQty {
            get {
                return ((int)(this["BenchmarkTestUdpClientsQty"]));
            }
            set {
                this["BenchmarkTestUdpClientsQty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16000")]
        public int BenchmarkTcpConnectStatePort {
            get {
                return ((int)(this["BenchmarkTcpConnectStatePort"]));
            }
            set {
                this["BenchmarkTcpConnectStatePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BenchmarkAddEnvironmentParametersToResult {
            get {
                return ((bool)(this["BenchmarkAddEnvironmentParametersToResult"]));
            }
            set {
                this["BenchmarkAddEnvironmentParametersToResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedResultsNetworkTestsFolderPath {
            get {
                return ((string)(this["SavedResultsNetworkTestsFolderPath"]));
            }
            set {
                this["SavedResultsNetworkTestsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ReconnectQtyComunicateTcpClient {
            get {
                return ((int)(this["ReconnectQtyComunicateTcpClient"]));
            }
            set {
                this["ReconnectQtyComunicateTcpClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReconnectQtyBenchmarkComunicateTcpClient {
            get {
                return ((int)(this["ReconnectQtyBenchmarkComunicateTcpClient"]));
            }
            set {
                this["ReconnectQtyBenchmarkComunicateTcpClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ReconnectTimeoutComunicateTcpClient {
            get {
                return ((int)(this["ReconnectTimeoutComunicateTcpClient"]));
            }
            set {
                this["ReconnectTimeoutComunicateTcpClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReconnectTimeoutBenchmarkComunicateTcpClient {
            get {
                return ((int)(this["ReconnectTimeoutBenchmarkComunicateTcpClient"]));
            }
            set {
                this["ReconnectTimeoutBenchmarkComunicateTcpClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoStartTcpConnect {
            get {
                return ((bool)(this["AutoStartTcpConnect"]));
            }
            set {
                this["AutoStartTcpConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStartTestTcpConnect {
            get {
                return ((bool)(this["AutoStartTestTcpConnect"]));
            }
            set {
                this["AutoStartTestTcpConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMessageShowOnAbortMainConnection {
            get {
                return ((bool)(this["IsMessageShowOnAbortMainConnection"]));
            }
            set {
                this["IsMessageShowOnAbortMainConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double NotificationOpacity {
            get {
                return ((double)(this["NotificationOpacity"]));
            }
            set {
                this["NotificationOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyAdamThreeCategoryState {
            get {
                return ((bool)(this["BlocklyAdamThreeCategoryState"]));
            }
            set {
                this["BlocklyAdamThreeCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlocklyAdamTwoCategoryState {
            get {
                return ((bool)(this["BlocklyAdamTwoCategoryState"]));
            }
            set {
                this["BlocklyAdamTwoCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyAdamThreeCategoryAlternateName {
            get {
                return ((string)(this["BlocklyAdamThreeCategoryAlternateName"]));
            }
            set {
                this["BlocklyAdamThreeCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyAdamTwoCategoryAlternateName {
            get {
                return ((string)(this["BlocklyAdamTwoCategoryAlternateName"]));
            }
            set {
                this["BlocklyAdamTwoCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlocklyAdamCommonCategoryState {
            get {
                return ((bool)(this["BlocklyAdamCommonCategoryState"]));
            }
            set {
                this["BlocklyAdamCommonCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyAdamCommonCategoryAlternateName {
            get {
                return ((string)(this["BlocklyAdamCommonCategoryAlternateName"]));
            }
            set {
                this["BlocklyAdamCommonCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlocklyDateTimeCategoryState {
            get {
                return ((bool)(this["BlocklyDateTimeCategoryState"]));
            }
            set {
                this["BlocklyDateTimeCategoryState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlocklyDateTimeCategoryAlternateName {
            get {
                return ((string)(this["BlocklyDateTimeCategoryAlternateName"]));
            }
            set {
                this["BlocklyDateTimeCategoryAlternateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adam")]
        public string ApiLogin {
            get {
                return ((string)(this["ApiLogin"]));
            }
            set {
                this["ApiLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adam1234")]
        public string ApiPassword {
            get {
                return ((string)(this["ApiPassword"]));
            }
            set {
                this["ApiPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5147")]
        public int ApiPort {
            get {
                return ((int)(this["ApiPort"]));
            }
            set {
                this["ApiPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckServerVersion {
            get {
                return ((bool)(this["CheckServerVersion"]));
            }
            set {
                this["CheckServerVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7071")]
        public int LogServerPort {
            get {
                return ((int)(this["LogServerPort"]));
            }
            set {
                this["LogServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeExtendedExecuteReportToggleSwitchState {
            get {
                return ((bool)(this["ChangeExtendedExecuteReportToggleSwitchState"]));
            }
            set {
                this["ChangeExtendedExecuteReportToggleSwitchState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DontShowBrowserMenuInBlockly {
            get {
                return ((bool)(this["DontShowBrowserMenuInBlockly"]));
            }
            set {
                this["DontShowBrowserMenuInBlockly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int SoketServerPort {
            get {
                return ((int)(this["SoketServerPort"]));
            }
            set {
                this["SoketServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppThemeName {
            get {
                return ((string)(this["AppThemeName"]));
            }
            set {
                this["AppThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateUserDirrectory {
            get {
                return ((bool)(this["CreateUserDirrectory"]));
            }
            set {
                this["CreateUserDirrectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLineNumber {
            get {
                return ((bool)(this["ShowLineNumber"]));
            }
            set {
                this["ShowLineNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditorIsReadOnly {
            get {
                return ((bool)(this["EditorIsReadOnly"]));
            }
            set {
                this["EditorIsReadOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double SourceEditorLength {
            get {
                return ((double)(this["SourceEditorLength"]));
            }
            set {
                this["SourceEditorLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double WebViewZoomFactor {
            get {
                return ((double)(this["WebViewZoomFactor"]));
            }
            set {
                this["WebViewZoomFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowVideo {
            get {
                return ((bool)(this["ShowVideo"]));
            }
            set {
                this["ShowVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double PopupPanelHeight {
            get {
                return ((double)(this["PopupPanelHeight"]));
            }
            set {
                this["PopupPanelHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double SSHPanelHeight {
            get {
                return ((double)(this["SSHPanelHeight"]));
            }
            set {
                this["SSHPanelHeight"] = value;
            }
        }
    }
}
